spring.application.name=product-service
spring.data.mongodb.uri=mongodb://root:password@localhost:27017/product?authSource=admin

#observability endpoints
management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=product-service
management.tracing.sampling.probability=1.0
# by default spring will only generate tracing for 10% of requests, but we want to trace for all the requests